#! /bin/sh


S_VERSION="3.3.3-2"   # 3.3.3-1 was broken :(
set -e

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ] ; then
  if dpkg --compare-versions "$2" lt-nl "$S_VERSION"; then
	

	RET=""
	db_get sysstat/remove_files || true
	RETVAL="$RET"
	db_stop || true
	if [ "$RETVAL" = "true" ]; then
		echo "Removing old statistics from /var/log/sysstat" 1>&2 
	 	rm -f /var/log/sysstat/sa[0-9]*
	fi
	
  fi
fi


if [ "$1" = "configure" ] ; then

  if ! update-alternatives --display sar | grep -q '^/usr/bin/sar\.sysstat' 
  then
       update-alternatives --install /usr/bin/sar sar /usr/bin/sar.sysstat 0 \
		--slave /usr/share/man/man1/sar.1.gz sar.1.gz \
					/usr/share/man/man1/sar.sysstat.1.gz
  fi
fi

#DEBHELPER#

exit 0

