#!/bin/sh
# vim:ts=4:et
# $Id: sysstat.postrm 1525 2011-06-16 21:17:32Z robert $

PACKAGE="sysstat"
DEFAULT="/etc/default/$PACKAGE"

set -e
# remove logfiles and default file when package is purged
if [ "$1" =  "purge" ] ; then
    rm -rf /var/log/sysstat
    rm -f "$DEFAULT"
    which ucf >/dev/null && ucf --purge "$DEFAULT"
    which ucfr >/dev/null && ucfr --purge "$PACKAGE" "$DEFAULT"
fi

#DEBHELPER#

exit 0
